#!/usr/bin/ksh

OWNERIP=$(getent hosts `hostname` | awk '{print $1}')
for IP in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 ; do \
   pntadm -A 192.168.127.1${IP} -i 010012712701${IP} \
   -s ${OWNERIP} -m stub127 -f 01 \
   -c "Build zone on stub127" 192.168.127.0; done

# -A – the client IP address (or hostname known via /etc/hosts, technically);
# -i – the client identifier (MAC address prefixed by the ARP code for the type of network, usually 01 for Ethernet);
# -s – DHCP server responsible for the leases;
# -m – the client macro for common settings;
# -f – the flag describing the lease type (01 = PERMANENT lease; announced via DHCP and never expires to be recycled for other clients);
# -c – an optional comment describing this client;
# The final parameter is the subnet name (as it is known by the DHCP server).
